services:
  db:
    image: postgres:15.6
    restart: always
    environment:
      POSTGRES_DB: trip_db
      POSTGRES_USER: trip_user
      POSTGRES_PASSWORD: trip_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=trip_db
      - DB_USER=trip_user
      - DB_PASSWORD=trip_pass
      - DB_HOST=db

  web:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:8000

volumes:
  pgdata: